### ISSUE TITLE
Performance of format_with

### ISSUE THREAD

**Issue by u2** [ruby-grape/grape-entity#107]
We use `format_with` in our code.
```
module Grape
  class Entity
    format_with(:iso_timestamp) { |dt| dt.utc.iso8601 if dt }
  end
end
```
```
with_options(format_with: :iso_timestamp) do
    expose :created_at
    expose :updated_at
end
```
But when I saw newrelic.
![c90e26d0-fff6-480a-bbda-40b64217857d](https://cloud.githubusercontent.com/assets/161756/6099909/bd8eeaa2-b03f-11e4-8342-72136e1b404c.png)
![0c53ba27-017c-4ab4-a6b8-865571523a1e](https://cloud.githubusercontent.com/assets/161756/6099918/ef38cb72-b03f-11e4-9c89-03d1d715bd14.png)
So why `format_with` consume so much time?Any device for optimizing?
What about use cache `method_missing` to rewrite this method?

**Comment by u2** [comment]
Sorry, I made a mistake.It's `Grape::Middleware::Formatter#call`,not `format_with`.It's reasonable for `Grape::Middleware::Formatter#call` to consume so much time, right?

**Comment by dblock** [comment]
So it's rendering of an entity to json, right? You should have more details inside that part and see what the breakdown there is. In a project we've switched rendering to [oj](https://github.com/ohler55/oj) for example and got a 30% improvement.

**Comment by marshall-lee** [comment]
Newrelic plots like this one above are very familiar to me from my work.

`Grape::Middleware::Formatter` consumes large time, that's right. But note that this time is not only the time spent in the `Grape::Middleware::Formatter` code:

1. It's a `Grape::Entity` exposure logic that I'm trying to optimize.
2. It's also a  methods calls (done by `Grape::Entity`) to an object/objects you're representing. Every exposure is a method call to an object. This method calls could be heavy, especially if you use `ActiveRecord` (query building, etc). For example, we saved a lot of CPU time when switched to ElasticSearch (using Chewy).
3. And, of course, it's a JSON rendering.

So, all that stuff happens in just one middleware: `Grape::Middleware::Formatter`.

1 and 2 (and probably 3 too) could be optimized by introducing a cache layer, i'm working on this idea now.

**Comment by dblock** [comment]
FWIW we use [Garner](https://github.com/artsy/garner) at API level and [mongoid-cached-json](https://github.com/dblock/mongoid-cached-json) for JSON rendering.

**Comment by marshall-lee** [comment]
@dblock this is good, but `Grape::Entity` still lacks russian doll caching for nesting entities. This is something that could optimize rendering itself.

**Comment by viren140290** [comment]
> So it's rendering of an entity to json, right? You should have more details inside that part and see what the breakdown there is. In a project we've switched rendering to oj for example and got a 30% improvement.

@dblock Is that project open source? If so could you may be post a link?
