### ISSUE TITLE
how to split entity define from model into another directory?

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape-entity#171]
I have define entity into `app/api/v1/entities/user.rb` with following code:

```ruby
class User::Entity < Grape::Entity
  expose :user_phone
  expose :user_nickname
  expose :user_qq
  expose :wx
  expose :laiwang
  expose :gong_xian_month do |entity|
    entity.gongxian :month
  end
  expose :gong_xian_all do  |entity|
    entity.gongxian :all
  end
end
```

But when test from rails console , it throw me error:

```
NameError: uninitialized constant User::Entity
```

**Comment by marshall-lee** [comment]
Rails?

File names should match class names and directory nesting should match namespace nesting. Read more about how `config.autoload_paths` works, it's not a `Grape::Entity` issue.

**Comment by TangMonk** [comment]
@marshall-lee thanks for your reply, I am using anther way(`ActiveSupport::Concern`)

in `app/api/entities/user_entity.rb`:

```
module UserEntity
  extend ActiveSupport::Concern
  included do
    class Entity < Grape::Entity
      expose :user_phone
      expose :user_nickname
      expose :user_qq
      expose :wx
      expose :laiwang
      expose :gong_xian_month do |entity|
        entity.gongxian :month
      end
      expose :gong_xian_all do  |entity|
        entity.gongxian :all
      end
    end    
  end
end
```

and include in `app/models/user.rb`: 

```
class User < ActiveRecord::Base
  include PzzUserEntity
end
```

It is better?

**Comment by marshall-lee** [comment]
IMHO, [no](https://en.wikipedia.org/wiki/Single_responsibility_principle).

Concerns are mostly for extracting reusable (generic) functionality.

**Comment by TangMonk** [comment]
thanks @marshall-lee 

But If I define with following in `app/api/entities/user.rb`

```
class User
  class Entity < Grape::Entity
    expose :user_phone
    expose :user_nickname
    expose :user_qq
    expose :wx
    expose :laiwang
    expose :gong_xian_month do |entity|
      entity.gongxian :month
    end
    expose :gong_xian_all do  |entity|
      entity.gongxian :all
    end
  end    
end
```

Then I cannot start server, because of `devise` problem:

```
in `raise_no_devise_method_error!': User does not respond to 'devise' method. This usually means you haven't loaded your ORM file or it's being loaded too late. To fix it, be sure to require 'devise/orm/YOUR_ORM' inside 'config/initializers/devise.rb'
```

**Comment by marshall-lee** [comment]
I say, your problem is only that you named your file wrong and put it in a wrong folder. That's all.

**Comment by TangMonk** [comment]
thanks @marshall-lee 

But I put it in autoload_paths

in `application.rb`

```
config.autoload_paths << "#{Rails.root}/app/api/v1/entities/"
```

And I can execute `User::Entity` from rails console, it means the file is loaded.

**Comment by marshall-lee** [comment]
I didn't advice you to touch `autoload_paths`, I adviced you just *learn* about how it works :)

If you haven't touched it before then just name your class `V1::Entities::UserEntity` *because* your file is named `v1/entities/user_entity.rb`. They just should match, otherwise Rails cannot know in what file search requested class.

I strongly advice anyone who use api versioning to separate functionality by namespaces (`V1`, `V2`, ...). So you should have `V1::UsersAPI` and `V1::Entities::UserEntity` because they both are the `/v1/...` api logic.


BUT If you just want something *simple*, then read about [including `Grape::Entity::DSL`](https://github.com/ruby-grape/grape-entity#using-the-exposure-dsl). It is messing model logic with presentation logic but probably it's enough for small applications.

**Comment by TangMonk** [comment]
@marshall-lee, thanks

Use module for namespace is ok.

But `grape-entity` could not auto-detect model's entity (`User::Entity`), So we will use `present user, with: V1::Entities::UserEntity` over and over again, I thnk It is not comfortable

**Comment by marshall-lee** [comment]
You can define your own helper, applying *convention over configuration* principle:
```ruby
def v1_present(object, options)
  unless options[:with]
    options[:with] = "V1::Entities::#{object.class}Entity"
  end
  present object, options
end
```

**Comment by TangMonk** [comment]
@marshall-lee , wow, I am sorry for my stupid, thanks!
