### ISSUE TITLE
options[:version] is not set in Entity

### ISSUE THREAD

**Issue by chigginsiii** [ruby-grape/grape-entity#184]
From the docs:

> The option keys :version and :collection are always defined.

I've tried exposing :version with a block and with a method, both are coming up "null". I've dumped the :env keys and it's not there. 

Searching through this repository, I don't see anywhere that this would be set by default.

Am I just looking over that four leaf clover or is the above correct?

**Comment by dblock** [comment]
Does your API have a `version`? It comes from [here](https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/inside_route.rb#L311) in Grape.
