### ISSUE TITLE
Nested exposure doesn't work

### ISSUE THREAD

**Issue by dmitry** [ruby-grape/grape-entity#191]
This code:

```ruby
class User < Grape::Entity
  expose :photo do |p|
    expose :large do
      p.photo.url(:large)
    end
  end
end
```

Returns:

```
NoMethodError (undefined method `expose' for #<API::User:0x00000023cdec68>):
```

grape-entity: v0.4.8
grape: v0.13.0

**Comment by dblock** [comment]
Did you try this on HEAD? I think the fixes and support for nested exposures hasn't been released yet. We have tests for this, https://github.com/ruby-grape/grape-entity/blob/2baf103f5a0574a4d83a7453b2fbeec998a6a46d/spec/grape_entity/entity_spec.rb#L88. 

cc: @idyll @marshall-lee maybe time to release 0.5.0 ...

**Comment by dmitry** [comment]
I saw it, but haven't tried, as we are depending on https://github.com/ruby-grape/grape-swagger here. Thought it's available for 0.4.x as well, but the 0.5.x has better implementation of the nested exposures. Looks like I need to work on https://github.com/ruby-grape/grape-swagger/issues/314 first :)

**Comment by namxam** [comment]
@dmitry Have you managed to get this to work? I think we are currently running into the same issues here.

**Comment by dmitry** [comment]
@namxam you can upgrade to 0.5, it should be fixed there. I've solved it by not using nested exposures :)

**Comment by dblock** [comment]
I believe this is fixed, closing.
