### ISSUE TITLE
expose "using" without wrapped name.

### ISSUE THREAD

**Issue by pisaq** [ruby-grape/grape-entity#194]
class Foo < Grape::Entity
    expose :id, :name, :description,
end

class FoosList < Grape::Entity
  expose(:foo, using: Entities::Foo){ |f| f }
end

Can I achive soething like this but without having evrywhere "foo" :

 [ "foo": {}, "foo": {}, "foo": {} ] 

vs.

[{}, {}, {}]

Thanks!

**Comment by dan-corneanu** [comment]
Please provide a full example of your code. I do not really understand what you are trying to achieve. If you simply want to represent a list of object using the Foo entity then you can use something like this:
```
class FooEntity < Grape::Entity
	expose :id, :name, :description
end

foos = []
foos << { id: 10, name: 'Foo Bar 10', description: 'Just a test'}
foos << { id: 11, name: 'Foo Bar 11', description: 'Just a test'}

data = FooEntity.represent foos
puts data.to_json

# result is
# [{"id":10,"name":"Foo Bar 10","description":"Just a test"},{"id":11,"name":"Foo Bar 11","description":"Just a test"}]
```

An entity knows how to represent collections, you do not need to define a new entity for the collection itself. Is this what you were looking after?

**Comment by pisaq** [comment]
Thanks @dan-corneanu ,

My point was just resolved here: https://github.com/avyy/grape-entity/commit/4a47b953ddf702b8cd64a6f1bb599c5bdaf160b5

Beautiful!
