### ISSUE TITLE
attribute column delegate_attribute error

### ISSUE THREAD

**Issue by peterwillcn** [ruby-grape/grape-entity#197]
```
+-----------+------------------+------+-----+---------+----------------+
| Field     | Type             | Null | Key | Default | Extra          |
+-----------+------------------+------+-----+---------+----------------+
| id        | int(11) unsigned | NO   | PRI | NULL    | auto_increment |
| xxx       | varchar(64)      | NO   | MUL |         |                |
| attribute | varchar(64)      | NO   |     |         |                |
| xx        | char(2)          | NO   |     | =       |                |
| xx        | varchar(253)     | NO   |     |         |                |
+-----------+------------------+------+-----+---------+----------------+
```
```
module V2
  module Entities
    class xxx < Grape::Entity
      #expose :id, :group name, :op, :value, :attribute # output this :attribute error
      expose :id, :groupname, :op, :value, :read_attribute
      private
      def read_attribute
	      object.inspect
      end
    end
  end
end
```
==>
```
  {
    "id": 1,
    "xxx": "user",
    "read_attribute": "#<xxx id: 1, xxx: \"user\", attribute: \"Auth-Type\", xx: \":=\", xxx: \"Local\">",
    "xxx": "xxx",
    "xxx": "Local"
  }
....
```

Rails ActiveRecord use gem safe_attributes solve it, 
see https://github.com/bjones/safe_attributes/blob/master/lib/safe_attributes/base.rb
But,grape-entity is error
  web/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/read.rb:98:in `attribute'
web/vendor/bundle/ruby/2.2.0/gems/grape-entity-0.4.8/lib/grape_entity/delegator/plain_object.rb:6:in `delegate'
web/vendor/bundle/ruby/2.2.0/gems/grape-entity-0.4.8/lib/grape_entity/entity.rb:590:in `delegate_attribute'
web/vendor/bundle/ruby/2.2.0/gems/grape-entity-0.4.8/lib/grape_entity/entity.rb:581:in `value_for'
web/vendor/bundle/ruby/2.2.0/gems/grape-entity-0.4.8/lib/grape_entity/entity.rb:442:in `block in serializable_hash'
web/vendor/bundle/ruby/2.2.0/gems/grape-entity-0.4.8/lib/grape_entity/entity.rb:439:in `each'
web/vendor/bundle/ruby/2.2.0/gems/grape-entity-0.4.8/lib/grape_entity/entity.rb:439:in `each_with_object'
web/vendor/bundle/ruby/2.2.0/gems/grape-entity-0.4.8/lib/grape_entity/entity.rb:439:in `serializable_hash'

**Comment by peterwillcn** [comment]
@dblock  This not a bug, I find solve way see change **attribute** column name to **attr** fix it. vary thank you... 
https://github.com/FreeRADIUS/freeradius-server/issues/1472

**Comment by dblock** [comment]
I'll close this I suppose, but generally name collisions aren't great, we should try to avoid them.
