### ISSUE TITLE
Present Collection of Entities and Total Count

### ISSUE THREAD

**Issue by Linell** [ruby-grape/grape-entity#201]
I've got a resource that looks something like:

```
get '/stuff' do
    present @service.get_data, :only => @only
end
```

When `@service.get_data` returns a collection of entities everything works perfectly. _But_ I need to paginate through this data on the client, so I need to also return the total number of records. To do this, my first thought is to just make `@service.get_data` return something like 

```
{
  :total => 102,
  :data => same_stuff_it_was_returning_before
}
```

The problem with that is that now the present method can't recognize the class of things that it needs to be actually presenting. So the object is just presented as is. This also means that the only parameter doesn't work.

What is the recommended way of making something like this work?

**Comment by dblock** [comment]
Here you're presenting a different type of object, so your `@service.get_data` would return a hash with these two things (or something like that). Another option is to return the total count in a header instead.

The total count suffers from the problem that items might change across multiple calls, so with this approach you're going to see duplicate items if something was deleted as you paginate, and will miss items if something was added. So generally, I encourage you to look at a Hypermedia format like HAL and construct real cursors (next links). My example in https://github.com/ruby-grape/grape-with-roar has built-in support for exactly this scenario, paginated presenters for collections of objects. 

The Grape mailing list could be more helpful for questions like these, closing.
