### ISSUE TITLE
BigDecimal data fields are presented as strings

### ISSUE THREAD

**Issue by IlyaBeliaev** [ruby-grape/grape-entity#208]
Hello.

When I pass an ActiveRecord model with BigDecimal fields into present(…,with: GrapeEntity) method it generates json with strings instead of numbers.

For example, if the model contains a “cost” field which is BigDecimal type, the generated json looks like:

```
{
  cost: "123.50"
}
```

This looks wrong to me. Is this its right behaviour?

**Comment by dblock** [comment]
Looks like a bug indeed.

**Comment by chlebta** [comment]
Got same issue decimals are exposed as strings

**Comment by jibiel** [comment]
Turned out it's a [Rails peculiarity](https://github.com/rails/rails/pull/12183/commits/4d02296cfbd69b4d2757dfd20f23d778bb23b81b). The issue can be closed. /cc @dblock

**Comment by ro-savage** [comment]
@dblock @jibiel - Surely this is a bug. Rails doesn't control the JSON spec. Numbers should not be strings. This breaks the json specification, it also means the documentation in grape is wrong as the generated docs show the value as a float despite it being returned as a string.

**Comment by jibiel** [comment]
1. `Grape::Entity` relies on the `ActiveSupport` for the JSON representation of the data types. No point in fighting it at the same time as it would complicate the general codebase for the sake of a single case.

2. You can easily change any output format to your liking with `format_with`:

```ruby
format_with :float do |attribute|
  attribute.to_f
end
```

3. Haven't seen any float response attribute examples in the docs, so it's probably not so obvious problem. If you've got bitten by the misleading documentation you should consider creating an issue or a fix for it in the appropriate repo.

**Comment by dblock** [comment]
@ro-savage If there's something that can be done in grape-entity, consider making a PR and we can see if it makes sense to merge here.
