### ISSUE TITLE
Kernel methods get priority over delegate methods

### ISSUE THREAD

**Issue by maltoe** [ruby-grape/grape-entity#215]
Hi,

Question: Due to the way exposures are looked up in the entity class first (calling `respond_to attribute, true`), attributes defined on the delegate class that collide with `Kernel` methods can not be exposed. We today noticed that with a AR model that has a `belongs_to :system` association. Probably poor wording on our side, but still: What would be the preferred way to deal with this? Currently we need to monkey-patch `Grape::Entity#delegate_attribute`.

```
class Foo < ActiveRecord::Base
  belongs_to :system

  class Entity < Grape::Entity
    expose :system
  end
end
```

Thanks,
Malte

**Comment by Linell** [comment]
I've ran into the same problem before, and the way that I handled it was 

```ruby
class Foo < ActiveRecord::Base
  belongs_to :system

  class Entity < Grape::Entity
    expose :system do |foo, options|
      foo.system
    end
  end
end
```

It's not great, but it works.

**Comment by dblock** [comment]
Is there something we can do about this in grape-entity?

**Comment by maltoe** [comment]
Sure, setting [this](https://github.com/ruby-grape/grape-entity/blob/master/lib/grape_entity/entity.rb#L481) to `false`. But there's a spec testing specifically for this, so I guess you guys were presented with a use case for allowing private methods of the Entity to take priority over the delegator's attribute.

You could also just exclude methods not owned by the entity class, á la

```
def delegate_attribute attribute
  if respond_to?(attribute, true) && method(attribute).owner == self.class
   ...
```

**Comment by maltoe** [comment]
@Linell Thanks, that would work. Unfortunately, we actually do not have the Entity classes in the model classes themselves (gave that example for simplicity), so we usually have something like
```
module Entities
  class Foo < Grape::Entity
    expose :system, using: Entities::System
  end
end
```
