### ISSUE TITLE
Latest ruby version support and dependencies

### ISSUE THREAD

**Issue by avyy** [ruby-grape/grape-entity#233]
We did not specified `active_support, rack, json` versions in `gemspec` and `Gemfile`, so last update of those gems broke our travis [builds](https://travis-ci.org/ruby-grape/grape-entity/builds/141552591), because those gems require `ruby >= 2.2.2` and travis configured to run specs on ruby `1.9.3 .. 2.3`.

We specified needed versions of dependencies to pass travis' tests on all configured platforms temporarily [(see gemspec and Gemfile)](https://github.com/ruby-grape/grape-entity/commit/c5abc1bc83ee01f8cb23b4e77e21846bcb733157). But we have to make a choice what to do next: use latest versions of dependencies or support old rubies.

What do you think? :suspect:

**Comment by dblock** [comment]
I am not in love with the idea of requiring Ruby 2.2 on HEAD for all Grape projects just because ActiveSupport 5 does. I suggest trying to condition the dependencies in `Gemfile` and remove any version locking in `.gemspec` next. Something like this:

Gemfile:

```ruby
if RUBY_VERSION ...
gem 'activesupport', '~> 4...'
elsif ...
gem 'activesupport', '~> 5...'
end
```

What do you think?

**Comment by nbulaj** [comment]
You can use different gemfiles and test them against different versions of gems, like it done here: [doorkeeper-sequel/blob/master/.travis.yml](https://github.com/nbulaj/doorkeeper-sequel/blob/master/.travis.yml).

**Comment by dblock** [comment]
Looking forward to some PRs!
