### ISSUE TITLE
warning: redefining `object_id' may cause serious problems.

### ISSUE THREAD

**Issue by ahmgeek** [ruby-grape/grape-entity#241]
I have two columns in most of our `DB` tables, `object_type` and `object_id`. I saw a weird behavior when exposing them with grape entity, that they map to Entity's ruby `obejct_id` instead of the  model attribute.
when I redefined them in the entity like

``` RUBY
expose :object_id, documentation: { type: 'Integer', desc: 'Notification Object ID' }
expose :object_type, documentation: { type: 'String', desc: 'Notification Object Type' }

private

def object_id
  object.object.uid if object
end
```

I got this warning `warning: redefining 'object_id' may cause serious problems.`

**Comment by LeFnord** [comment]
@ahmgeek … this is expected, cause you're redefining it …

rewrite your example should solve it …

```ruby
expose :foo, as: :object_id, documentation: { type: 'Integer', desc: 'Notification Object ID' }

private

def foo
  object.object.uid if object
end
```

**Comment by owahab** [comment]
@LeFnord that explains how to circumvent the warning but doesn't explain the reason why it happened. Could you please elaborate.

**Comment by LeFnord** [comment]
maybe this helps 😉 

we have an object – here it represents an instance of an model – as a result of a request,
this is what `grape` response with
```ruby
present :some_object_name, object, with: Entities::ForObject
```

the entity maybe looks like:
```ruby
module Entities
  class ForObject < Grape::Entity
    expose :id, as: :'$guid' documentation: { type: Integer, … }
    expose :name, as: :display_name, documentation: { type: String, … }
    expose :formatted, as: :other_name, documentation: { type: String, … }
    expose :attr_1, documentation: { type: String, … }
  end
end
```

if `:as` given, this is always the name of the key in the result (response),
and the data comes always from the first argument (e.g. `:name`),
this can be:

- an attribute: `object.attribute`
- or more general, a method to which the object responds to: `object.method`

means:
```ruby
...
expose :foo, as: :bar
...

def foo
  "#{itme_code}--#{description}"
end
```
overwrites the date given by `bar`

**Comment by ahmgeek** [comment]
@LeFnord I guess you explained the workaround not why grape-entity can't handle the `object_id` model attribute. In rails I guess if I have an `object_id` attribute in my `Package`  model for instance, and that attribute woks with his brother `object_type` for the polymorphic feature, rails will never respond with the `object_id` that ruby produce for the object's memory unique id, right ?
it will get the data from database and map it to the attribute.
grape don't do this, I can use grape-entity's `as:` but we needed an explain for that behavior.

**Comment by dblock** [comment]
I think this can be closed, or are there action items from here?

**Comment by ahmgeek** [comment]
@dblock I still don't know if the behavior is normal or intended. but it doesn't make sense to expose a ruby `object_id` instead of `object_id` table attribute

**Comment by LeFnord** [comment]
@ahmgeek … my explanation above doesn't describe a workaround, it describes how grape-entity works
and yeah, your are overwriting the `object_id`, which every ruby object has, as you mentioned above
