### ISSUE TITLE
Grape DSL: Defining multiple return entities

### ISSUE THREAD

**Issue by Razer6** [ruby-grape/grape-entity#242]
Consider an API endpoint which returns a different entity depending on the current user. Is it possible to specify those different return entities in Grape DSL? Something like the following?

```ruby
desc 'Return user details' do
  success Entities::BasicUser, Entities::FullUser
end
get 'users' do
  if is_admin
    present users, with: Entities::FullUser
  else
    present users, with: Entities::BasicUser
  end
end
```

**Comment by Koilanetroc** [comment]
Is it implemented? As I can see in version 1.6.2, if I pass multiple entities separated by comma, it raises an ArgumentError: `strict_hash_configuration.rb:51:in block (2 levels) in simple_settings_methods: wrong number of arguments (given 2, expected 1) (ArgumentError)`
