### ISSUE TITLE
release 0.5.2

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape-entity#243]
@marshall-lee @idyll 

I can do it this week if nobody's around

**Comment by dblock** [comment]
@LeFnord you were also quite active here recently, lmk if you want to pitch in!

**Comment by LeFnord** [comment]
@dblock … if it is urgent, do it; but I can also do it this evening (from my private machine)

**Comment by dblock** [comment]
I don't think there's anything urgent :)
