### ISSUE TITLE
is_array: true not compatible with  param_type: 'body'

### ISSUE THREAD

**Issue by lumean** [ruby-grape/grape-entity#252]
Hi,
I have the following entities:
```ruby
module Entity

  class Account < Grape::Entity
    expose :cma, documentation: { type: Integer, desc: 'Company number', param_type: 'body'}
    expose :name, documentation: { type: String, desc: 'Company Name' }
    expose :environment, documentation: { type: String, desc: 'Test Environment' }
    expose :sites, documentation: { type: Integer, desc: 'Amount of sites' }
    expose :username, documentation: { type: String, desc: 'Username for Dashboard' }
    expose :password, documentation: { type: String, desc: 'Password for Dashboard' }
  end
  
  class Accounts < Grape::Entity
    expose :accounts, documentation: { type: Entity::Account, is_array: true, param_type: 'body', required: true } 
  end
  
end # module Entity
```
and use it as follows in my endpoint:
```ruby
module Api
  class Accounts < Grape::API
    desc 'createTestAccount',
       params: Entity::Accounts.documentation
    post 'create' do
      JSON(params)
    end
  end
end
```
But when I generate the swagger documentation for it  i still get param_type formData:

![grafik](https://cloud.githubusercontent.com/assets/9656676/20669724/0abd6276-b576-11e6-9c40-0574f9211f15.png)

What do I need to change that I get the following JSON in the model / example swagger:
```
{
  "accounts": [
    {
      "cma": 0,
      "name": "string",
      "environment": "string",
      "sites": 0,
      "username": "string",
      "password": "string"
    }
  ]
}
```
When I omit  ```is_array: true``` I'm able to get the proper nesting and param_type body, but of course the array is missing then...
Any suggestions are appreciated.

**Comment by LeFnord** [comment]
Hi @lumean … think it isn't thge right repo for you question, it would be better placed in grape-swagger …

you have to define the success entity and that the response is an array
```ruby
desc 'create account',
      is_array: true,
      params: Entities::Accounts.documentation,
      success: Entities::Accounts
post do
  # your code goes here
end
```
… and yeap the request parameters should be in body, not formData, it seems that it is a grape-swagger issue

**Comment by LeFnord** [comment]
@lumean … use grape-swagger from master and try it
