### ISSUE TITLE
Specifying related resource URI's for Grape entities

### ISSUE THREAD

**Issue by oswaldoferreira** [ruby-grape/grape-entity#259]
Is there a known DRY way of specifying related resource URI's to a given `Grape::Entity`? 

Taking Github API as example (https://developer.github.com/v3/issues/), they're able to present a list of related resource URI's for each resource on their responses. Would be great to be able to do it without manually specifying each URI on `expose`. 

Would appreciate any thoughts on this.

**Comment by LeFnord** [comment]
please ask it in the [grape google group](https://groups.google.com/forum/#!forum/ruby-grape)
