### ISSUE TITLE
version 0.5.2 issue

### ISSUE THREAD

**Issue by giedriusr** [ruby-grape/grape-entity#260]
Hello,

I have an entity

```ruby
# entity
module API
  module Entities
    class Event < Grape::Entity
      include API::Entities::CommonFields
      
      # .. some other exposed fields
    end
  end
end

# concern
module API
  module Entities
    module CommonFields
      extend ActiveSupport::Concern

      included do
        expose :url
      end

      def url
        "url string"
      end
    end
  end
end
```

With version 0.5.1 all works fine. I tried to switch to 0.5.2 and my specs started failing. If I don't use the concern, everything comes back to its place and it works. But I need to share common exposures.
My environment:
```
Using grape-entity 0.5.2
Using mustermann-grape 0.4.0
Using grape 0.19.1
Using grape-middleware-logger 1.7.1
Using grape-rails-cache 0.1.2
Using grape-swagger 0.25.3
Using kaminari-grape 1.0.1
Using grape-kaminari 0.1.9

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
```

I get:
```ruby
NoMethodError:
       undefined method `url' for #<Event:0x007fdb996360b0>
```

From what I understand it is related to the fix of https://github.com/ruby-grape/grape-entity/pull/217. How can I fix it?

Thanks

**Comment by LeFnord** [comment]
can you reproduce the behavior with the actual version?

**Comment by giedriusr** [comment]
@LeFnord not sure if I understood you correctly. Current version 0.5.1 where functionality works. In 0.5.2 seems like it ignores the concern and tries to look for url in the event AR model.

**Comment by LeFnord** [comment]
no, I mean with the actual version 0.6.1

**Comment by giedriusr** [comment]
@LeFnord it doesn't so I started to downgrade version by version and noticed that 0.5.2 is the breaking one.

**Comment by giedriusr** [comment]
Anyone else having the same issue?

**Comment by LeFnord** [comment]
Hi @giedriusr  … I'm using your code … with following endpoint:
```ruby
module Api
  module Endpoints
    class Event < Grape::API
      namespace :event do
        desc 'get event',
             success: Entities::Event
        get do
          # your code goes here
        end
      end
    end
  end
end
```
and the Entities same as above, run it under grape-entity 0.5.1 and 0.6.1, and have for both versions the same result:
```json
"Event": {
  "type": "object",
  "properties": {
    "url": {
      "type": "string"
    }
  },
  "description": "get event"
}
```

its a bit strange, cause I can not re-produce it …

**Comment by giedriusr** [comment]
@LeFnord thanks, I see. Will work on further investigation then. I will close the issue for the time being.
