### ISSUE TITLE
What is the difference between `with` and `using`?

### ISSUE THREAD

**Issue by dosuken123** [ruby-grape/grape-entity#270]
1. `expose :stages, with: StageEntity`
2. `expose :stages, using: StageEntity`

Seems exact same effect.

**Comment by dblock** [comment]
It's `present :with` and `expose :using`, how're you getting the same result? maybe `StageEntity` is implied in the first case?

**Comment by dosuken123** [comment]
@dblock  Hmm, I had the same thought with you, however,

`expose :detailed_status, as: :status, with: StatusEntity`
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/serializers/pipeline_entity.rb#L15

`expose :stages, using: StageEntity`
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/serializers/pipeline_entity.rb#L18

Even If I exchange `using` <-> `with` for each line, [the relative spec](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/spec/serializers/pipeline_entity_spec.rb) doesn't get an error. It seems working correctly.

Ofcouse, `with: Whatever` caught an exception.

**Comment by dblock** [comment]
Even if the class `Whatever` exists?

**Comment by dosuken123** [comment]
Thank you for advice. Probably the `with` is declared somewhere not in this gem. I'll try to find it.

**Comment by dblock** [comment]
I could be wrong, you can always write a spec to demonstrate an issue!
