### ISSUE TITLE
Documentation Request - how to return a value instead of a key value pair

### ISSUE THREAD

**Issue by aronlmin** [ruby-grape/grape-entity#273]
```javascript
{
  "access_key": {
    "token": "zESPnSKr08JslfO9Xz4sNAMVtFfPZKQmdw1qfzF3xd"
  }
}
```
Id like to make a documentation request for returning *only* the value instead of the object or key/value pair from the entity

my api endpoint looks something like
```ruby
## Entity
class AccessKey < Grape::Entity
  expose :token
end

## Endpoint
post '/' do
  # .... auth stuff
  user = BACKBONE::User.find_by(params[:email])
  access_key = BACKBONE::AccessKey.new_key_for_user(user)
  present :access_key, access_key, with: BACKBONE::Entities::AccessKey
end

```

The goal would be to return
```javascript
{
  "access_key": "zESPnSKr08JslfO9Xz4sNAMVtFfPZKQmdw1qfzF3xd"
}
```

**Comment by LeFnord** [comment]
@aronlmin … its more a question, so the [mailing-list](https://groups.google.com/forum/#!forum/ruby-grape) would be a better place 😉 

… as you said it, you have return the value instead the entity, means try this:
```ruby
post do
  key = '# some foo'
  present :access_key, key
end
```

**Comment by aronlmin** [comment]
how funny -_- I way over thought this -_-
