### ISSUE TITLE
how can I expose an avatar image url?

### ISSUE THREAD

**Issue by Davidzhu001** [ruby-grape/grape-entity#275]
how can i expose an avatar image url?

**Comment by Linell** [comment]
Assuming you've got a method on your model that returns the URL, so that something like this works correctly:

```ruby
your_model.avatar_url
```

Then you entity is as simple as actually exposing that method like you do any other.

```ruby
expose :avatar_url
```

**Comment by Davidzhu001** [comment]
i meant computed url, and now i got it. Thanks
