### ISSUE TITLE
Loosening ActiveSupport version to 3?

### ISSUE THREAD

**Issue by ericschultz** [ruby-grape/grape-entity#289]
I currently am using Rails 3.2 and would like to use grape-entity. Is there any reason why the Activesupport version couldn't be loosened to 3? I know it was loosened to 4 in the past. 

If this would be alright, I'd be happy to do any sort of testing necessary. The unit tests pass for me on with `'activesupport', '>= 3.0.0'` so I'm not sure if there's any other testing required.

**Comment by LeFnord** [comment]
Hi @ericschultz the only reason is, that the people shouldn't use old gems, but yeah loose it, or remove the version completely, we will see what's happen 😉

**Comment by LeFnord** [comment]
see my comment on the PR
