### ISSUE TITLE
Can't expose same field more than once

### ISSUE THREAD

**Issue by jnardone** [ruby-grape/grape-entity#296]
ref: https://github.com/ruby-grape/grape-entity/pull/295

In our code we expose the same field more than once, using different formatters e.g.

```
    class Entity < Grape::Entity
        expose :useragent, format_with: :ua_to_os, safe: true, as: :os
        expose :useragent, format_with: :ua_to_browser, safe: true, as: :browser
    end
```

(these `format_with` formatters call some helper methods on some 3rd party code to extract the appropriate bits)  The formatters don't matter though - as the UT in the pull request shows, any use of the field more than once exhibits the problem.

However, starting in 0.7.0, only the last exposure for a given field is represented - all the others are now missing from the output.  I think (but am not sure) that @DmitryTsepelev's changes in https://github.com/ruby-grape/grape-entity/pull/292 might be the culprit. 

Note that the example above (and in the PR as well), there is no class hierarchy - all of these inherit direct from `Grape::Entity`.

**Comment by DmitryTsepelev** [comment]
@jnardone let me take a look

**Comment by DmitryTsepelev** [comment]
@jnardone Okay, investigated a bit and found out that according to the https://github.com/ruby-grape/grape-entity/issues/286 which I was trying to fix we wanted to allow overriding condition in the inherited models (see the example in the issue). However, in your case, we want to allow multiple exposures with the different keys exposed from the same model.
I see two possible solutions here:
1. Improve my condition from the previous PR in a way that it knows where the exposure comes from and, if the class is the same - do not replace it with the next one, if it's a child class - replace according to the other conditions.
2. Allow setting up a special key (e.g. `override_parent`) in the child class and set the default to `false`

cc @LeFnord thoughts?

**Comment by DmitryTsepelev** [comment]
Example implementation of 2 is here https://github.com/DmitryTsepelev/grape-entity/commit/ac8bf226df5a3250f09c2c443ba1b65644d886d1 please let me know if you're ok with that and I'll make a PR shortly

**Comment by jnardone** [comment]
An alternate idea would be - for your #286 fix, only consider it to be a duplicate if the field AND the formatter AND the `as` are unique?  So

```
expose :a
expose :a as :z
```

would only expose `z` but 

```
expose :a, format_with: :foo, as: :a1
expose :a, format_with: :bar, as: a2
expose :a
```

would output all 3 exposures, because they contain distinct modifiers?

**Comment by DmitryTsepelev** [comment]
@jnardone even easier https://github.com/DmitryTsepelev/grape-entity/commit/58a8530e08e3283641a165e2d10c6814626601d0 we need to choose between these two.

**Comment by LeFnord** [comment]
Hi @DmitryTsepelev, @jnardone …
sorry, for late replay … 

I personally would be prefer a more general solution, to not to introduce possibl;e side-effects (as here), so @DmitryTsepelev your first suggestion (https://github.com/DmitryTsepelev/grape-entity/commit/ac8bf226df5a3250f09c2c443ba1b65644d886d1) is a good candidate, if you can do it, please also add an entry in the README, there the new option will be described, thanks

**Comment by DmitryTsepelev** [comment]
@LeFnord sure, done

**Comment by LeFnord** [comment]
Hi @jnardone can you have a look on the mörged PR of @DmitryTsepelev (https://github.com/ruby-grape/grape-entity/pull/297) and test this solution, so if iti is ok, I will realease a patch version

**Comment by jnardone** [comment]
@LeFnord @DmitryTsepelev this looks great on our end.

**Comment by DmitryTsepelev** [comment]
👍

**Comment by LeFnord** [comment]
0.7.1 released
