### ISSUE TITLE
Same name nested arguments get value from root

### ISSUE THREAD

**Issue by renatolond** [ruby-grape/grape-entity#362]
Hello! Thanks for the work in grape-entity :)

I was testing adding it to a project and I found a behavior which is not documented, so I'm not sure what's the intended result.

I have the following, simplified, representation:
```
  class MyEntity < Grape::Entity
    expose :bar
    expose :foo do
      expose :bar
    end
  end
```
I expected that doing this:
```
MyEntity.represent({bar: 1, foo: { bar: 2 }}).to_json
```
Would give me `{"bar":1,"foo":{"bar":2}}` but it's giving me `{"bar":1,"foo":{"bar":1}}`

The same also happens if I only represent bar:

```
> puts MyEntity.represent({bar: 1}).to_json
{"bar":1,"foo":{"bar":1}}
```

Is this expected behavior? Am I building the Entity in an unexpected way?

**Comment by LeFnord** [comment]
mmh … think this is not intended … please can you pack it inito a spec, thanks

**Comment by renatolond** [comment]
Here is a spec that shows the issue:
```
# frozen_string_literal: true

require 'spec_helper'

describe 'Nested arguments with the same name' do
  class User < Grape::Entity
    expose :name
    expose :email
    expose :work do
      expose :company
      expose :email
    end
  end

  let(:entity) { User }
  let(:model) { double(attributes) }
  let(:attributes) do
    {
      name: 'River Song',
      email: 'river@song.com',
      work: {
        company: 'Song Ltd',
        email: 'contact@song.com'
      }
    }
  end

  describe '#represent' do
    it 'the represented json should match the original hash' do
      expect(JSON.parse(User.represent(attributes).to_json, symbolize_names: true)).to eq(attributes)
    end
  end
end
```

**Comment by renatolond** [comment]
Hey folks :)
We were wondering if there's some bounty program you work with that could help finance the project and fix specific issues and if so which one? We would be willing to put up a bounty for this issue.

**Comment by dblock** [comment]
@renatolond it's nice of you to offer! You probably will have better success hiring a developer on your side to fix the issues you care most about, maintainers here are pretty responsive to good PRs.

**Comment by renatolond** [comment]
Hi!
I started working on a PR to fix this but realized there was a test for this already, I just had misunderstood the docs. This spec does what I was trying to do: https://github.com/ruby-grape/grape-entity/blob/master/spec/grape_entity/hash_spec.rb#L23-L29

Thanks again for the attention and sorry for the issue!
