### ISSUE TITLE
Inheritance issue with the entity

### ISSUE THREAD

**Issue by hay-wtag** [ruby-grape/grape-entity#364]
```
module API
  module V1
    module Entities
      class A < Grape::Entity
        expose :status 

        def status
         'HI'
        end
      end
    end
  end
end

```
```
module API
  module V101
    module Entities
      class A < V1::Entities::A
        expose :status

        def status
         'BYE'
        end
      end
    end
  end
end
```

In this case, when I am calling the **V101** it is calling the `status` function of `V1` instead of the `V101`. This code perfectly works with the **grape-entity version - 0.4.8**. After v**ersion 0.5 >=** this code does not behave normally like before. Ami I missing something? Thank you!

**Comment by ssa-wtag** [comment]
What do you mean by `does not behave normally`? @hay-wtag

**Comment by chr-wtag** [comment]
@ssa-wtag  This issue is not related to the `grape-entity` and can thus be closed.  In the original code, there was an explicit call to the parent via another entity which caused this inheritance to fail!
