### ISSUE TITLE
entity documentation  support for array of entities?

### ISSUE THREAD

**Issue by chebyte** [ruby-grape/grape-entity#66]
hi there I have the following grape-entites

````
module HQ
  module Entities
    class Client < Grape::Entity
      expose :created_by_id, documentation: {type: Integer, desc: "Created by id"}
      expose :updated_by_id, documentation: {type: Integer, desc: "Updated by id"}
      expose :first_name,    documentation: {type: String, desc: 'First Name.'}
      expose :last_name,     documentation: {type: String, desc: 'Last Name.'}
      expose :zipcode,       documentation: {type: String, desc: 'Zip Code.'}
      expose :emails, using: HQ::Entities::Email, documentation: {type: ::Item, desc: 'Emails.'}
    end
  end
end

module HQ
  module Entities
    class Email < Grape::Entity
      expose :address, documentation: {type: Integer, desc: "Email"}
    end
  end
end

````

the problem that I need that swagger generate the UI with the complex form I means client has many emails

````
      expose :emails, using: HQ::Entities::Email, documentation: {type: Array, desc: 'Emails.'}
````

what type I need to use? I added array but it show me just as string field like this

https://www.evernote.com/shard/s143/sh/a53f78c8-5599-4148-811f-e6b7617cd13a/419383ac0d5d9e5bac0a06278ac481da

**Comment by igormoochnick** [comment]
I'm trying to figure out the same thing. The 'is_array' flag doesn't change anything on the swagger side.
Am I missing anything too?

**Comment by igormoochnick** [comment]
Just submitted a pull request for grape-swagger that fixes the issue for the 'is_array' on return entity: https://github.com/tim-vandecasteele/grape-swagger/pull/206

**Comment by siriniok** [comment]
Perphars, this issue should be closed already.
https://github.com/ruby-grape/grape-swagger/pull/206

**Comment by dblock** [comment]
Yes.
